### ISSUE TITLE
Tabs list overlapping with current page

### ISSUE THREAD

**Issue by happiestplants** [ranmaru22/firefox-vertical-tabs#29]
Hi I've been using this for a while now and love it. However, I started having an issue yesterday with the tabs list overlapping with the current page I'm on. 
In the screenshot, the last tab is the page open. The mouse cursor isn't show in the screenshot but it is hovering in the white space next to the tab above it. I've tried reinstalling the CSS and the tab center reborn and nothing changed.
I hope I explained it well enough, thanks for the help!
![image](https://user-images.githubusercontent.com/19482287/176504949-c7efd929-2375-419e-b187-29999175f7b4.png)

**Comment by codewzrd** [comment]
It most likely has to do with the version of Firefox. I just updated it to v103 and I'm having the same issue. Could be an issue with Tab Center Reborn plugin as well with this version of Firefox.

![image](https://user-images.githubusercontent.com/23690/176517593-a810ee6b-da23-45b8-981f-3ebfc4d7f57b.png)

**Comment by mrBOIz** [comment]
I'm having the same issue here on latest Nightly 104.0a1
It started misbehaving on Friday or sometime last week, if I'm not mistaken

**Comment by spa5k** [comment]
Having this error since yesterday.

**Comment by ranmaru22** [comment]
I think I found the problem. I appended the hover handler to the sidebar, but only changed the non-hover size of the `sidebar-box` area (which is what contains Tab Center. Seems like that leaves an invisible area that doesn't interfere with browsing but does catch mouse events.

No idea why that was not an issue before, but changing that seems to be working. I'll post a fix soon.

**Comment by ranmaru22** [comment]
I pushed a fix with #30. This changes both userChrome.css and tabCenterReborn.css.

Unfortunately with the changes in the userChrome, some of the smoother animations I had in TCR don't work anymore so they had to go.

For more details, see the PR commit.

**Comment by happiestplants** [comment]
Thanks for the fixes! I don't know if anyone is experiencing this as well but I can't use the exit and minimize buttons on the top left of my browser anymore. It wasn't working before the bug was fixed and it still isn't now either. I am using a custom theme which makes the buttons appear but when I disable the theme the buttons don't appear at all. 

Thanks for the help!
